"""Add foreign key relationship between Users and ChatSessions

Revision ID: f752408e1fb0
Revises: c9cd5ab608c8
Create Date: 2025-06-26 13:05:39.357954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f752408e1fb0'
down_revision: Union[str, None] = 'c9cd5ab608c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'user_id')
    # ### end Alembic commands ###
